test_that("a term whose block moves is simulated from its own model", {
  set.seed(41)
  dd <- data.frame(x = sort(stats::runif(400, 0, 10)))

  # THE CHECK the earlier version failed: seg's block is a Jacobian, so
  # X %*% beta is a linearization about the term's starting position and the
  # contribution is term_value at the coefficients given. Simulating from the
  # first gives data from a different model, and the two differ by the whole
  # nonlinearity.
  truth <- c(0, 2, 6)
  sim <- rstatmod(y ~ 0 + seg(x, psi = 2), gaussian1_distrib(), dd,
                  par = list(mu = truth, sigma = log(0.05)))
  th <- sim$theta$mu
  sl <- diff(th) / diff(dd$x)
  expect_equal(stats::median(sl[dd$x[-1] < 5]), truth[[1L]], tolerance = 1e-6)
  expect_equal(stats::median(sl[dd$x[-1] > 7]), truth[[2L]], tolerance = 1e-6)

  # and a fit reads it back
  fit <- statmod(y ~ 0 + seg(x, psi = 2), gaussian1_distrib(), sim$data)
  expect_equal(unname(coef(fit, readable = FALSE)$mu), truth,
               tolerance = 0.05)
})

test_that("a nonlinear term is simulated at its own parameters", {
  set.seed(42)
  dd <- data.frame(x = stats::runif(300, 0.1, 4))
  fm <- y ~ 0 + nl(~ a * exp(-r * x), start = list(a = 1, r = 1))
  sim <- rstatmod(fm, gaussian1_distrib(), dd,
                  par = list(mu = c(4, 0.4), sigma = log(0.05)))
  expect_equal(sim$theta$mu, 4 * exp(-0.4 * dd$x),
               tolerance = 1e-10)
  expect_equal(unname(coef(statmod(fm, gaussian1_distrib(), sim$data),
                           readable = FALSE)$mu),
               c(4, 0.4), tolerance = 0.05)
})

test_that("the coefficients may be a number or a function of the count", {
  set.seed(43)
  dd <- data.frame(x = stats::runif(60), g = factor(rep(letters[1:4], 15)))
  a <- rstatmod(y ~ x + g, gaussian1_distrib(), dd, par = list(mu = 0.5))
  expect_equal(unname(a$par$mu), rep(0.5, 5L))

  # the equation carries the group's block AND the intercept beside it, so
  # the count is the design's rather than the factor's
  b <- rstatmod(y ~ random(~ 1 | g), gaussian1_distrib(), dd,
                par = list(mu = function(k) rep(2, k)))
  expect_gte(length(b$par$mu), nlevels(dd$g))
  expect_true(all(b$par$mu == 2))

  # a function that answers with the wrong count is reported rather than
  # recycled into a different model
  expect_error(rstatmod(y ~ x, gaussian1_distrib(), dd,
                        par = list(mu = function(k) 1)),
               "returned 1 value where")
})

test_that("a model with no covariates needs only a row count", {
  set.seed(44)
  s <- rstatmod(y ~ 1, gaussian1_distrib(), n = 25,
                par = list(mu = 3, sigma = log(0.1)))
  expect_identical(nrow(s$data), 25L)
  expect_equal(mean(s$data$y), 3, tolerance = 0.1)
  # the truth comes back beside the data rather than attached to it, so a
  # row subset cannot leave a theta of the original length behind
  expect_length(s$theta$mu, 25L)
  expect_error(rstatmod(y ~ 1, gaussian1_distrib()), "give 'data'")
  expect_error(rstatmod(y ~ 1, gaussian1_distrib(), data.frame(x = 1:3),
                        n = 5), "'n' is 5 and 'data' has 3")
})

test_that("a response that is not a symbol is rejected", {
  dd <- data.frame(x = stats::runif(20))
  # the model generates log(y), so neither name would be honest
  expect_error(rstatmod(log(y) ~ x, gaussian1_distrib(), dd),
               "must be a symbol")
  expect_error(rstatmod(cens(y, y, "observed") ~ x, gaussian1_distrib(), dd),
               "censored response is not simulated")
})

test_that("a score-driven series is generated by its own recursion", {
  set.seed(45)
  dd <- data.frame(t = 1:2000)
  truth <- list(omega = 0.4, alpha1 = 0.3, pacf1 = 0.6)
  sim <- rstatmod(y ~ 0 + gas(p = 1, q = 1, time = t), gaussian1_distrib(),
                  dd, par = list(sigma = 0), structural = truth)
  # the level moves, which is what says the recursion ran: at the term's own
  # starting values it barely would
  expect_gt(stats::sd(sim$latent), 0.1)

  expect_equal(sim$structural[names(truth)], truth)
  fit <- statmod(y ~ 0 + gas(p = 1, q = 1, time = t), gaussian1_distrib(),
                 sim$data)
  z <- statmod_structural_state(statmod_design(fit@spec))$zeta[[1L]]
  got <- structural_psi(fit@spec@terms$mu[[1L]], z)
  for (q in names(truth)) {
    expect_equal(got[[q]], truth[[q]], tolerance = 0.15)
  }

  expect_error(rstatmod(y ~ 0 + gas(p = 1, q = 1, time = t),
                        gaussian1_distrib(), dd,
                        structural = list(beta1 = 0.5)),
               "not a parameter of this term")
  expect_error(rstatmod(y ~ 1, gaussian1_distrib(), n = 5,
                        structural = list(omega = 1)),
               "carries no")
})

test_that("a latent chain is drawn from the law the likelihood uses", {
  set.seed(46)
  sim <- rstatmod(y ~ 0 + regime(k = 2), gaussian1_distrib(),
                  data.frame(t = 1:1500), par = list(sigma = log(0.4)),
                  structural = list(level1 = -2, gap2 = 4))
  st <- sim$latent
  expect_identical(sort(unique(st)), 1:2)
  # each state's observations sit at that state's own level, which is what
  # says the path and the levels line up
  expect_equal(as.numeric(tapply(sim$data$y, st, mean)), c(-2, 2),
               tolerance = 0.1)
})

test_that("the truth comes back beside the data, not attached to it", {
  set.seed(47)
  dd <- data.frame(x = stats::runif(50))
  s <- rstatmod(y ~ x, gaussian1_distrib(), dd,
                par = list(mu = c(1, 2), sigma = log(0.3)))
  expect_s3_class(s, "StatmodSim")
  expect_named(s, c("data", "par", "theta", "latent", "structural",
                    "n_sim", "call"))
  expect_s3_class(s$data, "data.frame")
  expect_identical(names(s$par$mu), c("(Intercept)", "x"))
  expect_length(s$theta$mu, 50L)
  # every parameter is one value per observation, whether the equation
  # varies it or not, so a study can bind them to the rows
  expect_length(s$theta$sigma, 50L)

  # the shape is what a simulation study reads: the printed view says where
  # the two halves are rather than dumping the parameters at every row
  out <- utils::capture.output(print(s))
  expect_true(any(grepl("A simulation from a written model", out)))
  expect_true(any(grepl("the data is in $data", out, fixed = TRUE)))
  expect_false(any(startsWith(out, "$theta")))

  # and passing the whole result where a data frame was wanted is named
  expect_error(statmod(y ~ x, gaussian1_distrib(), s),
               "Pass its 'data' field", fixed = TRUE)
})

test_that("n_sim draws replicates that share one truth", {
  set.seed(48)
  dd <- data.frame(x = stats::runif(80, -2, 2))
  truth <- c(1, 2)
  s <- rstatmod(y ~ x, gaussian1_distrib(), dd, n_sim = 6,
                par = list(mu = truth, sigma = log(0.5)))
  expect_identical(s$n_sim, 6L)
  expect_length(s$data, 6L)
  expect_length(s$theta, 6L)
  # the truth is drawn ONCE and shared: replicates differ in what is random
  # and not in what is being estimated
  expect_equal(unname(s$par$mu), truth)
  expect_length(s$par, 2L)

  # with data rather than covariates the design is the same throughout,
  # which is what makes the study conditional on it
  expect_equal(s$data[[1L]]$x, s$data[[5L]]$x)
  # and the responses are not
  expect_false(isTRUE(all.equal(s$data[[1L]]$y, s$data[[5L]]$y)))
  # theta follows the design, so it does not move either
  expect_equal(s$theta[[1L]]$mu, s$theta[[5L]]$mu)

  # one replicate keeps the shape it had before n_sim existed
  one <- rstatmod(y ~ x, gaussian1_distrib(), dd,
                  par = list(mu = truth, sigma = log(0.5)))
  expect_s3_class(one$data, "data.frame")
  expect_true(is.numeric(one$theta$mu))
})

test_that("the covariates may be drawn afresh at every replicate", {
  set.seed(49)
  s <- rstatmod(y ~ x, gaussian1_distrib(), n = 60, n_sim = 5,
                par = list(mu = c(1, 2), sigma = log(0.5)),
                covariates = list(x = function(n) stats::runif(n, -2, 2)))
  # THE DISTINCTION the argument exists for: with `data` the design is held
  # and the study is conditional on it, with `covariates` it is drawn and the
  # study is over the design as well
  expect_false(isTRUE(all.equal(s$data[[1L]]$x, s$data[[3L]]$x)))
  expect_equal(unname(s$par$mu), c(1, 2))
  expect_true(all(vapply(s$data, nrow, integer(1)) == 60L))

  # a design that changes shape cannot take coefficients drawn against the
  # first one, so it is reported with the replicate rather than recycled
  expect_error(
    rstatmod(y ~ g, gaussian1_distrib(), n = 5, n_sim = 60,
             covariates = list(g = function(n)
               factor(sample(c("a", "b", "c"), n, TRUE)))),
    "design of another shape at replicate")

  expect_error(rstatmod(y ~ x, gaussian1_distrib(), n = 10,
                        covariates = list(x = 1:10)), "is not a function")
  expect_error(rstatmod(y ~ x, gaussian1_distrib(), n = 10,
                        covariates = list(x = function(n) 1)),
               "returned 1 value where")
  expect_error(rstatmod(y ~ x, gaussian1_distrib(), n = 10, n_sim = 0),
               "positive whole number")
})

test_that("a term with state draws a fresh path at every replicate", {
  set.seed(50)
  s <- rstatmod(y ~ 0 + gas(p = 1, q = 1, time = t), gaussian1_distrib(),
                data.frame(t = 1:300), n_sim = 3, par = list(sigma = 0),
                structural = list(omega = 0.4, alpha1 = 0.3, pacf1 = 0.6))
  expect_length(s$latent, 3L)
  expect_false(isTRUE(all.equal(s$latent[[1L]], s$latent[[2L]])))
  # the term's own parameters are shared, being part of the truth
  expect_equal(s$structural$alpha1, 0.3)
})
