# Documentation invariants that R CMD check does not enforce. The same file
# lives in all five packages of the toolkit, byte for byte apart from the
# package name: three of them once carried a weaker version, and the two
# weakest could not see the objects the strongest one found.

test_that("every exported object appears in the pkgdown index", {
  # pkgdown refuses to build a site with a topic missing from the reference
  # index, and it refuses IN CI, minutes after the push, for one line of YAML.
  skip_if_not_installed("pkgdown")
  root <- normalizePath("../..", mustWork = FALSE)
  skip_if_not(file.exists(file.path(root, "_pkgdown.yml")),
              "_pkgdown.yml not reachable from here")
  skip_if_not(rmarkdown::pandoc_available(), "pandoc not available")

  expect_no_error(pkgdown::check_pkgdown(pkg = root))
})

# man/ is reachable when the tests run from the source tree, which is where
# these checks belong; an installed package has no man/ to read.
man_dir <- function() if (dir.exists("../../man")) "../../man" else NULL

rd_info <- function(dir) {
  lapply(list.files(dir, pattern = "[.]Rd$", full.names = TRUE), function(f) {
    rd <- tools::parse_Rd(f)
    tags <- vapply(rd, function(x) attr(x, "Rd_tag"), character(1))
    grab <- function(tag) unlist(lapply(rd[tags == tag], function(x)
      trimws(paste(unlist(x), collapse = ""))))
    list(file = basename(f), name = grab("\\name"), aliases = grab("\\alias"),
         value = "\\value" %in% tags, example = "\\examples" %in% tags)
  })
}

# The Rcpp wrappers are generated by compileAttributes() and cannot carry
# roxygen; identified by what they are rather than by a list of names, so that
# adding a .cpp does not silently need this test edited.
#
# The second exclusion is S7's doing. `S7::method(coef, cls) <- fn` at the top
# level of a package expands to `coef <- \`method<-\`(coef, ...)`, so the base
# generic acquires a binding in the namespace. It is not the package's object
# and has no page of its own; the method it registers does.
documentable <- function() {
  ns <- asNamespace("statmodels7")
  nms <- setdiff(ls(ns, all.names = FALSE),
                 c("print", "plot", "summary", "mean", "simulate",
                   "coef", "confint", "logLik", "vcov",
                   "predict", "fitted", "residuals", "nobs", "formula",
                   "family", "weights", "df.residual", "sigma",
                   "model.matrix", "terms", "model.frame", "anova"))
  nms <- grep("^_statmodels7_", nms, invert = TRUE, value = TRUE)
  keep <- vapply(nms, function(n) {
    o <- get(n, envir = ns)
    !(is.function(o) && any(grepl(".Call", deparse(body(o)), fixed = TRUE)))
  }, logical(1))
  nms[keep]
}


test_that("every object in the package has a help topic", {
  # A man page's file name comes from its topic, and on a case-INSENSITIVE
  # filesystem two topics differing only in case are one file: the second
  # silently replaces the first, so a page exists on Linux and not here, and
  # nothing complains. The question that finds it is which object has no page,
  # asked on the machine where the evidence is destroyed.
  dir <- man_dir(); skip_if(is.null(dir), "man/ not reachable from here")
  documented <- unlist(lapply(rd_info(dir), `[[`, "aliases"))
  expect_equal(setdiff(documentable(), documented), character())
})


test_that("no two help topics collide when case is ignored", {
  # The same defect at its source, visible only where both files can exist. On
  # Windows one of the pair is already gone and this passes vacuously, which is
  # why the check above exists as well.
  dir <- man_dir(); skip_if(is.null(dir), "man/ not reachable from here")
  topics <- unlist(lapply(rd_info(dir), `[[`, "name"))
  low <- tolower(topics)
  clash <- unique(low[duplicated(low)])
  expect_equal(clash, character(),
               info = paste("topics differing only in case:",
                            paste(topics[low %in% clash], collapse = ", ")))
})


test_that("every exported topic has a value and an executable example", {
  # The two things a first CRAN submission is most often sent back for, and
  # neither is raised by R CMD check locally.
  dir <- man_dir(); skip_if(is.null(dir), "man/ not reachable from here")
  info <- rd_info(dir)
  exported <- getNamespaceExports(asNamespace("statmodels7"))

  expect_equal(setdiff(exported, unlist(lapply(info, `[[`, "aliases"))),
               character())

  # A package's landing page is not a function and by convention has no
  # \value; asking it for one would be asking what `?statmodels7` returns.
  # Two packages of the toolkit generate such a page and three do not, so the
  # exclusion is by what the page is rather than by whether it exists.
  is_pkg_page <- vapply(info, function(i) any(grepl("-package$", i$aliases)),
                        logical(1))
  is_exp <- vapply(info, function(i) any(i$aliases %in% exported), logical(1))
  no_value <- !is_pkg_page & vapply(info, function(i) !i$value, logical(1))
  no_example <- is_exp & !is_pkg_page &
    vapply(info, function(i) !i$example, logical(1))

  expect_equal(vapply(info[no_value], `[[`, character(1), "file"), character())
  expect_equal(vapply(info[no_example], `[[`, character(1), "file"),
               character())
})
