// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// coord_descent
List coord_descent(NumericMatrix X, NumericVector z, NumericVector w, NumericVector beta0, NumericMatrix cut, NumericMatrix slope, NumericMatrix icept, IntegerVector screen, int maxit, double tol, bool covariance);
RcppExport SEXP _statmodels7_coord_descent(SEXP XSEXP, SEXP zSEXP, SEXP wSEXP, SEXP beta0SEXP, SEXP cutSEXP, SEXP slopeSEXP, SEXP iceptSEXP, SEXP screenSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cut(cutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type icept(iceptSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type screen(screenSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(coord_descent(X, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance));
    return rcpp_result_gen;
END_RCPP
}
// coord_descent_sparse
List coord_descent_sparse(IntegerVector Ai, IntegerVector Ap, NumericVector Ax, int nrow, int ncol, NumericVector z, NumericVector w, NumericVector beta0, NumericMatrix cut, NumericMatrix slope, NumericMatrix icept, IntegerVector screen, int maxit, double tol, bool covariance);
RcppExport SEXP _statmodels7_coord_descent_sparse(SEXP AiSEXP, SEXP ApSEXP, SEXP AxSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP zSEXP, SEXP wSEXP, SEXP beta0SEXP, SEXP cutSEXP, SEXP slopeSEXP, SEXP iceptSEXP, SEXP screenSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type Ai(AiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ax(AxSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cut(cutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type icept(iceptSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type screen(screenSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type covariance(covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(coord_descent_sparse(Ai, Ap, Ax, nrow, ncol, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance));
    return rcpp_result_gen;
END_RCPP
}
// chol_rcond_cpp
double chol_rcond_cpp(NumericMatrix R, double anorm);
RcppExport SEXP _statmodels7_chol_rcond_cpp(SEXP RSEXP, SEXP anormSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type anorm(anormSEXP);
    rcpp_result_gen = Rcpp::wrap(chol_rcond_cpp(R, anorm));
    return rcpp_result_gen;
END_RCPP
}
// qr_factor_cpp
NumericMatrix qr_factor_cpp(NumericMatrix A, int threads);
RcppExport SEXP _statmodels7_qr_factor_cpp(SEXP ASEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(qr_factor_cpp(A, threads));
    return rcpp_result_gen;
END_RCPP
}
// xtv_cpp
NumericVector xtv_cpp(NumericMatrix X, NumericVector v, int threads);
RcppExport SEXP _statmodels7_xtv_cpp(SEXP XSEXP, SEXP vSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(xtv_cpp(X, v, threads));
    return rcpp_result_gen;
END_RCPP
}
// wxsq_cpp
NumericVector wxsq_cpp(NumericMatrix X, NumericVector w, int threads);
RcppExport SEXP _statmodels7_wxsq_cpp(SEXP XSEXP, SEXP wSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(wxsq_cpp(X, w, threads));
    return rcpp_result_gen;
END_RCPP
}
// xtx_cpp
NumericMatrix xtx_cpp(NumericMatrix A, int threads);
RcppExport SEXP _statmodels7_xtx_cpp(SEXP ASEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(xtx_cpp(A, threads));
    return rcpp_result_gen;
END_RCPP
}
// wcrossprod_cpp
NumericMatrix wcrossprod_cpp(NumericMatrix A, NumericVector w, NumericMatrix B, int threads);
RcppExport SEXP _statmodels7_wcrossprod_cpp(SEXP ASEXP, SEXP wSEXP, SEXP BSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(wcrossprod_cpp(A, w, B, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_statmodels7_coord_descent", (DL_FUNC) &_statmodels7_coord_descent, 11},
    {"_statmodels7_coord_descent_sparse", (DL_FUNC) &_statmodels7_coord_descent_sparse, 15},
    {"_statmodels7_chol_rcond_cpp", (DL_FUNC) &_statmodels7_chol_rcond_cpp, 2},
    {"_statmodels7_qr_factor_cpp", (DL_FUNC) &_statmodels7_qr_factor_cpp, 2},
    {"_statmodels7_xtv_cpp", (DL_FUNC) &_statmodels7_xtv_cpp, 3},
    {"_statmodels7_wxsq_cpp", (DL_FUNC) &_statmodels7_wxsq_cpp, 3},
    {"_statmodels7_xtx_cpp", (DL_FUNC) &_statmodels7_xtx_cpp, 2},
    {"_statmodels7_wcrossprod_cpp", (DL_FUNC) &_statmodels7_wcrossprod_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_statmodels7(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
