# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coord_descent <- function(X, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance) {
    .Call(`_statmodels7_coord_descent`, X, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance)
}

coord_descent_sparse <- function(Ai, Ap, Ax, nrow, ncol, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance) {
    .Call(`_statmodels7_coord_descent_sparse`, Ai, Ap, Ax, nrow, ncol, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance)
}

chol_rcond_cpp <- function(R, anorm) {
    .Call(`_statmodels7_chol_rcond_cpp`, R, anorm)
}

xtv_cpp <- function(X, v, threads) {
    .Call(`_statmodels7_xtv_cpp`, X, v, threads)
}

wxsq_cpp <- function(X, w, threads) {
    .Call(`_statmodels7_wxsq_cpp`, X, w, threads)
}

xtx_cpp <- function(A, threads) {
    .Call(`_statmodels7_xtx_cpp`, A, threads)
}

wcrossprod_cpp <- function(A, w, B, threads) {
    .Call(`_statmodels7_wcrossprod_cpp`, A, w, B, threads)
}

