# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coord_descent <- function(X, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance) {
    .Call(`_statmodels7_coord_descent`, X, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance)
}

coord_descent_sparse <- function(Ai, Ap, Ax, nrow, ncol, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance) {
    .Call(`_statmodels7_coord_descent_sparse`, Ai, Ap, Ax, nrow, ncol, z, w, beta0, cut, slope, icept, screen, maxit, tol, covariance)
}

chol_rcond_cpp <- function(R, anorm) {
    .Call(`_statmodels7_chol_rcond_cpp`, R, anorm)
}

