# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coord_descent <- function(X, z, w, beta0, cut, slope, icept, maxit, tol) {
    .Call(`_statmodels7_coord_descent`, X, z, w, beta0, cut, slope, icept, maxit, tol)
}

